"""Reform AnalysisTask

Revision ID: 03e31748c93d
Revises: dc29c98cb03c
Create Date: 2026-05-06 08:50:39.994113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e31748c93d'
down_revision: Union[str, Sequence[str], None] = 'dc29c98cb03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('class_type_ids', sa.ARRAY(sa.UUID()), nullable=True))
    op.drop_index(op.f('ix_analysis_tasks_callback_token'), table_name='analysis_tasks')
    op.drop_column('analysis_tasks', 'callback_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('callback_token', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_analysis_tasks_callback_token'), 'analysis_tasks', ['callback_token'], unique=True)
    op.drop_column('analysis_tasks', 'class_type_ids')
    # ### end Alembic commands ###
