"""add_process_values_to_taskstatus_enum

Revision ID: 166ac13397ca
Revises: 9f4976ef9ecf
Create Date: 2026-05-07 13:53:43.598468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166ac13397ca'
down_revision: Union[str, Sequence[str], None] = '9f4976ef9ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'processing'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
