"""add_new_values_to_taskstatus_enum

Revision ID: 9f4976ef9ecf
Revises: ec77a6b14c66
Create Date: 2026-05-07 13:51:40.410380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4976ef9ecf'
down_revision: Union[str, Sequence[str], None] = 'ec77a6b14c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'queued'")
    op.execute("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'failed'")
    op.execute("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'cancelled'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
