"""Add AnalysisTask

Revision ID: dc29c98cb03c
Revises: 661574a4ea4d
Create Date: 2026-05-04 12:14:05.046089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc29c98cb03c'
down_revision: Union[str, Sequence[str], None] = '661574a4ea4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('model_config_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='taskstatus'), nullable=True),
    sa.Column('callback_token', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('ws_session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['model_config_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tasks_callback_token'), 'analysis_tasks', ['callback_token'], unique=True)
    op.create_index(op.f('ix_analysis_tasks_image_id'), 'analysis_tasks', ['image_id'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_status'), 'analysis_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_ws_session_id'), 'analysis_tasks', ['ws_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_tasks_ws_session_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_status'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_image_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_callback_token'), table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    # ### end Alembic commands ###
